[package]
name = "tuple_len"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"
license = "MIT"
description = "macro to get the number of elements in a tuple"

[dependencies]
